apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: database
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: fleetman
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: database
  ports:
    - name: http
      port: 3306
  type: ClusterIP
